-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintGrammar.

module PrintGrammar where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsGrammar

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsGrammar.Ident where
  prt _ (AbsGrammar.Ident i) = doc $ showString i
instance Print AbsGrammar.Program where
  prt i = \case
    AbsGrammar.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print AbsGrammar.TopDef where
  prt i = \case
    AbsGrammar.FnDef type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print [AbsGrammar.TopDef] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsGrammar.Arg where
  prt i = \case
    AbsGrammar.Arg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])

instance Print [AbsGrammar.Arg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Block where
  prt i = \case
    AbsGrammar.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsGrammar.Stmt] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsGrammar.Stmt where
  prt i = \case
    AbsGrammar.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsGrammar.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsGrammar.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsGrammar.Ass id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsGrammar.AddArr id_ expr1 expr2 -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr1, doc (showString "]"), doc (showString "="), prt 0 expr2, doc (showString ";")])
    AbsGrammar.Incr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsGrammar.Decr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsGrammar.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsGrammar.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsGrammar.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsGrammar.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsGrammar.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsGrammar.For id_ expr1 expr2 stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 id_, doc (showString "in"), doc (showString "range"), doc (showString "("), prt 0 expr1, doc (showString ","), prt 0 expr2, doc (showString ")"), doc (showString ")"), prt 0 stmt])
    AbsGrammar.Repeat expr stmt -> prPrec i 0 (concatD [doc (showString "repeat"), prt 0 expr, prt 0 stmt])
    AbsGrammar.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    AbsGrammar.Break -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    AbsGrammar.Continue -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    AbsGrammar.Print expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])

instance Print AbsGrammar.Item where
  prt i = \case
    AbsGrammar.NoInit id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsGrammar.Init id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])
    AbsGrammar.NoInitArr id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsGrammar.InitArr id_ expr exprs -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]"), doc (showString "="), doc (showString "["), prt 0 exprs, doc (showString "]")])

instance Print [AbsGrammar.Item] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Expr] where
  prt 6 [] = concatD []
  prt 6 [x] = concatD [prt 6 x]
  prt 6 (x:xs) = concatD [prt 6 x, doc (showString ","), prt 6 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Type where
  prt i = \case
    AbsGrammar.Int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsGrammar.Str -> prPrec i 0 (concatD [doc (showString "string")])
    AbsGrammar.Bool -> prPrec i 0 (concatD [doc (showString "boolean")])
    AbsGrammar.Void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsGrammar.ConstInt -> prPrec i 0 (concatD [doc (showString "const"), doc (showString "int")])
    AbsGrammar.ConstStr -> prPrec i 0 (concatD [doc (showString "const"), doc (showString "string")])
    AbsGrammar.ConstBool -> prPrec i 0 (concatD [doc (showString "const"), doc (showString "boolean")])
    AbsGrammar.Array type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "[]")])
    AbsGrammar.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])

instance Print [AbsGrammar.Type] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Expr where
  prt i = \case
    AbsGrammar.Ekrotka exprs -> prPrec i 6 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    AbsGrammar.EArrayVar id_ expr -> prPrec i 6 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsGrammar.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsGrammar.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsGrammar.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    AbsGrammar.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    AbsGrammar.EApp id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsGrammar.EString str -> prPrec i 6 (concatD [printString str])
    AbsGrammar.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsGrammar.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsGrammar.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsGrammar.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsGrammar.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsGrammar.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsGrammar.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])

instance Print AbsGrammar.AddOp where
  prt i = \case
    AbsGrammar.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsGrammar.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsGrammar.MulOp where
  prt i = \case
    AbsGrammar.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsGrammar.Div -> prPrec i 0 (concatD [doc (showString "/")])
    AbsGrammar.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsGrammar.RelOp where
  prt i = \case
    AbsGrammar.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsGrammar.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsGrammar.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsGrammar.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsGrammar.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsGrammar.NE -> prPrec i 0 (concatD [doc (showString "!=")])
